
import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/footer'
import styles from './page.module.css'
import { ThemeProvider } from '../context/themeContext'
import AuthProvider from '@/components/AuthProvider/AuthProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Breizh Coffee Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
        <AuthProvider>
          <div className='container'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </AuthProvider>
      </ThemeProvider>
      </body>
    </html>
  )
}
